services:
  database:
    container_name: postgresql_database
    image: postgis/postgis:15-3.4
    restart: unless-stopped
    ports:
      - 127.0.0.1:${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data